// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMD27umSUyYykWnN6SUTjGqhD_h4M6lPw',
    appId: '1:693052659676:web:103a7fd27010077b452119',
    messagingSenderId: '693052659676',
    projectId: 'lojajaquelineandrade-803e7',
    authDomain: 'lojajaquelineandrade-803e7.firebaseapp.com',
    storageBucket: 'lojajaquelineandrade-803e7.firebasestorage.app',
    measurementId: 'G-YGSCG4FESR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyAstndjZSbukFd9mxMRHA1XSjva0Z0f0',
    appId: '1:693052659676:android:d91a1619adc4cfa3452119',
    messagingSenderId: '693052659676',
    projectId: 'lojajaquelineandrade-803e7',
    storageBucket: 'lojajaquelineandrade-803e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPR2Vq2_ezIwfJqhUWqecztiCCxsCSGEg',
    appId: '1:693052659676:ios:b9662327648b0fd3452119',
    messagingSenderId: '693052659676',
    projectId: 'lojajaquelineandrade-803e7',
    storageBucket: 'lojajaquelineandrade-803e7.firebasestorage.app',
    iosBundleId: 'com.example.lojajaqueline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPR2Vq2_ezIwfJqhUWqecztiCCxsCSGEg',
    appId: '1:693052659676:ios:b9662327648b0fd3452119',
    messagingSenderId: '693052659676',
    projectId: 'lojajaquelineandrade-803e7',
    storageBucket: 'lojajaquelineandrade-803e7.firebasestorage.app',
    iosBundleId: 'com.example.lojajaqueline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMD27umSUyYykWnN6SUTjGqhD_h4M6lPw',
    appId: '1:693052659676:web:9c1461b8b293b54a452119',
    messagingSenderId: '693052659676',
    projectId: 'lojajaquelineandrade-803e7',
    authDomain: 'lojajaquelineandrade-803e7.firebaseapp.com',
    storageBucket: 'lojajaquelineandrade-803e7.firebasestorage.app',
    measurementId: 'G-0MJMB90FTF',
  );
}
